//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestyDbTryout.EngraftDbManipulationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EngraftServiceSoap", Namespace="https://engraft.pl/")]
    public partial class EngraftService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ChangeStoppageTimeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EngraftService() {
            this.Url = global::TestyDbTryout.Properties.Settings.Default.TestyDbTryout_EngraftDbManipulationService_EngraftService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ChangeStoppageTimeCompletedEventHandler ChangeStoppageTimeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://engraft.pl/ChangeStoppageTime", RequestNamespace="https://engraft.pl/", ResponseNamespace="https://engraft.pl/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangeStoppageTime(int Id, System.DateTime StoppageTime, string UserName) {
            this.Invoke("ChangeStoppageTime", new object[] {
                        Id,
                        StoppageTime,
                        UserName});
        }
        
        /// <remarks/>
        public void ChangeStoppageTimeAsync(int Id, System.DateTime StoppageTime, string UserName) {
            this.ChangeStoppageTimeAsync(Id, StoppageTime, UserName, null);
        }
        
        /// <remarks/>
        public void ChangeStoppageTimeAsync(int Id, System.DateTime StoppageTime, string UserName, object userState) {
            if ((this.ChangeStoppageTimeOperationCompleted == null)) {
                this.ChangeStoppageTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeStoppageTimeOperationCompleted);
            }
            this.InvokeAsync("ChangeStoppageTime", new object[] {
                        Id,
                        StoppageTime,
                        UserName}, this.ChangeStoppageTimeOperationCompleted, userState);
        }
        
        private void OnChangeStoppageTimeOperationCompleted(object arg) {
            if ((this.ChangeStoppageTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeStoppageTimeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ChangeStoppageTimeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591